default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME_PREFIX']}_development" %>
  username: <%= "#{ENV['DATABASE_RAILS_USER']}" %>
  password: <%= "#{ENV['DATABASE_RAILS_USER_PW']}" %>
  host:     <%= "#{ENV['DATABASE_HOST']}" %>

staging:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME_PREFIX']}_staging" %>
  username: <%= "#{ENV['DATABASE_RAILS_USER']}" %>
  password: <%= "#{ENV['DATABASE_RAILS_USER_PW']}" %>
  host:     <%= "#{ENV['DATABASE_HOST']}" %>

production:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME_PREFIX']}" %>
  username: <%= "#{ENV['DATABASE_RAILS_USER']}" %>
  password: <%= "#{ENV['DATABASE_RAILS_USER_PW']}" %>
  host:     <%= "#{ENV['DATABASE_HOST']}" %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
